ontologies:
  - source: "ontology/modules/process/0.1/process.ttl"
    path: "ontology/modules/process/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/resource/0.1/resource.ttl"
    path: "ontology/modules/resource/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/actor/0.1/actor.ttl"
    path: "ontology/modules/actor/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/actorrole/0.1/actorrole.ttl"
    path: "ontology/modules/actorrole/"
    version: "0.1"
    latest: true