ontologies:
  - source: "ontology/modules/actor/0.1/actor.owl"
    path: "ontology/modules/actor/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/actor/0.0/actor.owl"
    path: "ontology/modules/actor/"
    version: "0.0"
  - source: "ontology/ceon/0.0/ceon.owl"
    path: "ontology/ceon/"
    version: "0.0"
    latest: true