ontologies:
  - source: "ontology/modules/process/0.1/process.ttl"
    path: "ontology/process/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/resource/0.1/resource.ttl"
    path: "ontology/resource/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/actor/0.1/actor.ttl"
    path: "ontology/actor/"
    version: "0.1"
    latest: true