ontologies:
  - source: "ontology/modules/resourceODP/0.1/resourceODP.ttl"
    path: "ontology/resourceODP/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/material/0.1/material.ttl"
    path: "ontology/material/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/product/0.1/product.ttl"
    path: "ontology/product/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/actorODP/0.1/actorODP.ttl"
    path: "ontology/actorODP/"
    version: "0.1"
