ontologies:
  - actor-0.1:
    source: "ontologies/modules/actor/0.1/actor.owl"
    path: "ontology/actor"
    version: "0.1"
    latest: true
  - actor-0.0:
    source: "ontologies/modules/actor/0.0/actor.owl"
    path: "ontology/actor"
    version: "0.0"
    latest: false