ontologies:
  - source: "ontology/modules/resourceODP/0.1/resourceODP.ttl"
    path: "ontology/resourceODP/"
    version: "0.1"
    latest: true
  - source: "ontology/modules/material/0.1/material.ttl"
    path: "ontology/material/"
    version: "0.1"
    latest: true
 