name: Publish docs
run-name: Building docs 🚀
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # - name: install wkhtmltopdf
      #  run: |
      #    wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
      #    sudo apt install ./wkhtmltox_0.12.6-1.focal_amd64.deb
        
      - name: install python packages
        run: pip install -r requirements.txt

      - name: install python playwright
        run: |
          pip intall playwright
          playwright install

      - name: build docs
        run: python build.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f docs/
          git commit -m "update docs" -a
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
